"""
Phase 5 — Report Generation

Produces professional vulnerability reports in three formats:
  • JSON  — machine-readable findings log
  • Markdown — human-readable report (convertible to HTML)
  • PDF  — styled executive report with charts and tables
"""

from __future__ import annotations

import json
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import TYPE_CHECKING

from rich.console import Console

from scanner.models import ScanResult, Severity

if TYPE_CHECKING:
    pass

console = Console()

DISCLAIMER = (
    "DISCLAIMER: This report was generated by an automated vulnerability scanner "
    "for authorized security testing purposes only. All scanning activities were "
    "performed with explicit authorization. Findings should be validated by a "
    "qualified security professional before remediation actions are taken."
)


# ══════════════════════════════════════════════════════════════════════════════
# JSON Report
# ══════════════════════════════════════════════════════════════════════════════

def save_json(result: ScanResult, path: Path) -> Path:
    """Write scan results as formatted JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(result.model_dump(mode="json"), f, indent=2, default=str)
    console.print(f"  [green]✓[/green] JSON report saved: {path}")
    return path


# ══════════════════════════════════════════════════════════════════════════════
# Markdown Report
# ══════════════════════════════════════════════════════════════════════════════

def save_markdown(result: ScanResult, path: Path) -> Path:
    """Render a Markdown vulnerability report."""
    path.parent.mkdir(parents=True, exist_ok=True)
    s = result.summary
    m = result.metadata

    lines: list[str] = []
    _add = lines.append

    _add("# 🛡️ Vulnerability Assessment Report\n")
    _add(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    _add(f"**Scanner Version:** {m.scanner_version}")
    _add(f"**Targets:** {', '.join(m.targets_requested)}")
    _add(f"**Scan Window:** {m.scan_start} → {m.scan_end}\n")
    _add(f"> {DISCLAIMER}\n")

    # Executive summary
    _add("## 📊 Executive Summary\n")
    _add(f"| Metric | Value |")
    _add(f"|--------|-------|")
    _add(f"| Hosts Scanned | {s.total_hosts} |")
    _add(f"| Hosts Up | {s.hosts_up} |")
    _add(f"| Open Ports | {s.total_ports_open} |")
    _add(f"| Total Findings | {s.total_findings} |")
    _add(f"| Overall Risk Score | **{s.overall_risk_score}/10** |")
    _add("")
    _add("### Findings by Severity\n")
    _add(f"| Severity | Count |")
    _add(f"|----------|-------|")
    _add(f"| 🔴 Critical | {s.critical_count} |")
    _add(f"| 🟠 High | {s.high_count} |")
    _add(f"| 🟡 Medium | {s.medium_count} |")
    _add(f"| 🔵 Low | {s.low_count} |")
    _add(f"| ⚪ Info | {s.info_count} |")
    _add("")

    # Methodology
    _add("## 🔍 Methodology\n")
    _add("This assessment was conducted using the following automated phases:\n")
    _add("1. **Asset Discovery** — Host discovery via ICMP/TCP probes")
    _add("2. **Port Scanning** — TCP port scanning with service version detection")
    _add("3. **Vulnerability Mapping** — CVE correlation via NVD database")
    _add("4. **Web Application Checks** — TLS, security headers, misconfigurations")
    _add("5. **Report Generation** — Automated findings aggregation and reporting\n")

    # Findings by host
    _add("## 🎯 Detailed Findings\n")

    for host in result.hosts:
        _add(f"### Host: {host.ip}" + (f" ({host.hostname})" if host.hostname else ""))
        _add(f"- **Status:** {host.status.value}")
        _add(f"- **OS Guess:** {host.os_guess or 'N/A'}")
        _add(f"- **Response Time:** {host.response_time_ms}ms\n")

        if host.ports:
            _add("#### Open Ports\n")
            _add("| Port | Protocol | Service | Version |")
            _add("|------|----------|---------|---------|")
            for p in host.ports:
                _add(f"| {p.port} | {p.protocol} | {p.service} | {p.version or 'N/A'} |")
            _add("")

        if host.findings:
            _add("#### Findings\n")
            # Sort by severity
            sorted_findings = sorted(
                host.findings,
                key=lambda f: list(Severity).index(f.severity)
            )
            for f in sorted_findings:
                sev_emoji = {"Critical": "🔴", "High": "🟠", "Medium": "🟡",
                             "Low": "🔵", "Info": "⚪"}.get(f.severity.value, "⚪")
                _add(f"##### {sev_emoji} [{f.severity.value}] {f.title}\n")
                _add(f"- **ID:** {f.id}")
                _add(f"- **Affected:** {f.host}:{f.port} ({f.service} {f.service_version})")
                if f.cve:
                    _add(f"- **CVSS Score:** {f.cve.cvss_score}")
                _add(f"- **Description:** {f.description}")
                _add(f"- **Evidence:** `{f.evidence}`")
                _add(f"- **Remediation:** {f.remediation}\n")
        else:
            _add("*No findings for this host.*\n")

    # Appendix
    _add("## 📎 Appendix\n")
    _add(f"- Scanner Version: {m.scanner_version}")
    _add(f"- Ports Scanned: {m.ports_scanned}")
    _add(f"- CVSS Threshold: {m.cvss_threshold}")
    _add(f"- Authorization Confirmed: {m.authorization_confirmed}")
    _add(f"\n---\n*{DISCLAIMER}*\n")

    path.write_text("\n".join(lines), encoding="utf-8")
    console.print(f"  [green]✓[/green] Markdown report saved: {path}")
    return path


# ══════════════════════════════════════════════════════════════════════════════
# PDF Report (ReportLab)
# ══════════════════════════════════════════════════════════════════════════════

def save_pdf(result: ScanResult, path: Path) -> Path:
    """Generate a professional PDF vulnerability report."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle,
        PageBreak,
        HRFlowable,
    )
    from reportlab.graphics.shapes import Drawing, String
    from reportlab.graphics.charts.piecharts import Pie

    path.parent.mkdir(parents=True, exist_ok=True)
    s = result.summary
    m = result.metadata

    doc = SimpleDocTemplate(
        str(path),
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=28, spaceAfter=6, textColor=colors.HexColor("#1E293B"),
        fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "CustomSubtitle", parent=styles["Normal"],
        fontSize=14, spaceAfter=20, textColor=colors.HexColor("#64748B"),
    )
    heading_style = ParagraphStyle(
        "CustomHeading", parent=styles["Heading1"],
        fontSize=18, spaceBefore=16, spaceAfter=10,
        textColor=colors.HexColor("#0F172A"),
        fontName="Helvetica-Bold",
    )
    subheading_style = ParagraphStyle(
        "CustomSubheading", parent=styles["Heading2"],
        fontSize=14, spaceBefore=12, spaceAfter=6,
        textColor=colors.HexColor("#334155"),
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "CustomBody", parent=styles["Normal"],
        fontSize=10, leading=14, alignment=TA_JUSTIFY,
        textColor=colors.HexColor("#334155"),
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"],
        fontSize=8, leading=10, textColor=colors.HexColor("#94A3B8"),
        alignment=TA_CENTER, spaceBefore=20,
    )

    story: list = []

    # ── Cover Page ────────────────────────────────────────────────────────
    story.append(Spacer(1, 2 * inch))
    story.append(Paragraph("🛡️ Vulnerability Assessment Report", title_style))
    story.append(Spacer(1, 0.3 * inch))
    story.append(HRFlowable(width="80%", thickness=2, color=colors.HexColor("#3B82F6")))
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", subtitle_style
    ))
    story.append(Paragraph(f"Targets: {', '.join(m.targets_requested)}", subtitle_style))
    story.append(Paragraph(f"Scanner Version: {m.scanner_version}", subtitle_style))
    story.append(Spacer(1, 1 * inch))
    story.append(Paragraph(
        f"Overall Risk Score: <b>{s.overall_risk_score}/10</b>", ParagraphStyle(
            "RiskScore", parent=styles["Normal"], fontSize=20, alignment=TA_CENTER,
            textColor=_risk_color(s.overall_risk_score),
            fontName="Helvetica-Bold",
        )
    ))
    story.append(Spacer(1, 1 * inch))
    story.append(Paragraph(DISCLAIMER, disclaimer_style))
    story.append(PageBreak())

    # ── Executive Summary ─────────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0")))
    story.append(Spacer(1, 0.2 * inch))

    summary_data = [
        ["Metric", "Value"],
        ["Total Hosts Scanned", str(s.total_hosts)],
        ["Hosts Online", str(s.hosts_up)],
        ["Open Ports Discovered", str(s.total_ports_open)],
        ["Total Vulnerabilities", str(s.total_findings)],
        ["Critical", str(s.critical_count)],
        ["High", str(s.high_count)],
        ["Medium", str(s.medium_count)],
        ["Low", str(s.low_count)],
        ["Informational", str(s.info_count)],
    ]

    summary_table = Table(summary_data, colWidths=[3 * inch, 2 * inch])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E293B")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.3 * inch))

    # Severity pie chart
    drawing = _severity_pie_chart(s)
    if drawing:
        story.append(Paragraph("Findings by Severity", subheading_style))
        story.append(drawing)
    story.append(Spacer(1, 0.2 * inch))

    # Top critical findings
    critical_findings = [
        f for h in result.hosts for f in h.findings
        if f.severity in (Severity.CRITICAL, Severity.HIGH)
    ]
    if critical_findings:
        story.append(Paragraph("Top Critical & High Findings", subheading_style))
        for cf in critical_findings[:5]:
            story.append(Paragraph(
                f"<b>{cf.severity.value}:</b> {_escape(cf.title)} — "
                f"{cf.host}:{cf.port}",
                body_style,
            ))
        story.append(Spacer(1, 0.1 * inch))

    story.append(PageBreak())

    # ── Methodology ───────────────────────────────────────────────────────
    story.append(Paragraph("Methodology", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0")))
    story.append(Spacer(1, 0.2 * inch))
    methodology_text = (
        "This automated vulnerability assessment was conducted in five phases: "
        "(1) Asset Discovery using ICMP and TCP probes to identify live hosts; "
        "(2) Port Scanning with service version detection to map open services; "
        "(3) Vulnerability Mapping by correlating services against the National "
        "Vulnerability Database (NVD) for known CVEs; "
        "(4) Web Application Checks including TLS configuration, HTTP security "
        "headers, and common misconfigurations; "
        "(5) Report Generation compiling all findings into this document."
    )
    story.append(Paragraph(methodology_text, body_style))
    story.append(PageBreak())

    # ── Detailed Findings ─────────────────────────────────────────────────
    story.append(Paragraph("Detailed Findings", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0")))
    story.append(Spacer(1, 0.2 * inch))

    all_findings = sorted(
        [(h, f) for h in result.hosts for f in h.findings],
        key=lambda x: list(Severity).index(x[1].severity)
    )

    if not all_findings:
        story.append(Paragraph("No vulnerabilities were detected.", body_style))
    else:
        # Findings summary table
        findings_table_data = [["#", "Severity", "Title", "Host", "Port"]]
        for idx, (host, finding) in enumerate(all_findings, 1):
            findings_table_data.append([
                str(idx),
                finding.severity.value,
                _truncate(finding.title, 40),
                finding.host,
                str(finding.port or "—"),
            ])

        ft = Table(findings_table_data, colWidths=[0.4 * inch, 0.8 * inch, 3 * inch, 1.3 * inch, 0.6 * inch])
        ft.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E293B")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))

        # Color-code severity cells
        for row_idx, (host, finding) in enumerate(all_findings, 1):
            sev_color = colors.HexColor(finding.severity.color)
            ft.setStyle(TableStyle([
                ("TEXTCOLOR", (1, row_idx), (1, row_idx), sev_color),
                ("FONTNAME", (1, row_idx), (1, row_idx), "Helvetica-Bold"),
            ]))

        story.append(ft)
        story.append(PageBreak())

        # Individual finding details
        for idx, (host, finding) in enumerate(all_findings, 1):
            sev_color = colors.HexColor(finding.severity.color)
            story.append(Paragraph(
                f"Finding #{idx}: {_escape(finding.title)}",
                ParagraphStyle("FindingTitle", parent=subheading_style, textColor=sev_color)
            ))
            story.append(Spacer(1, 0.05 * inch))

            detail_data = [
                ["Severity", finding.severity.value],
                ["ID", finding.id or "N/A"],
                ["Host", f"{finding.host}:{finding.port}"],
                ["Service", f"{finding.service} {finding.service_version}"],
            ]
            if finding.cve:
                detail_data.append(["CVSS Score", str(finding.cve.cvss_score)])
                detail_data.append(["CVSS Vector", finding.cve.cvss_vector or "N/A"])

            dt = Table(detail_data, colWidths=[1.2 * inch, 5 * inch])
            dt.setStyle(TableStyle([
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#475569")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]))
            story.append(dt)
            story.append(Spacer(1, 0.1 * inch))

            story.append(Paragraph("<b>Description:</b>", body_style))
            story.append(Paragraph(_escape(finding.description), body_style))
            story.append(Spacer(1, 0.05 * inch))

            story.append(Paragraph("<b>Evidence:</b>", body_style))
            evidence_style = ParagraphStyle(
                "Evidence", parent=body_style, fontName="Courier",
                fontSize=8, backColor=colors.HexColor("#F1F5F9"),
                leading=11, leftIndent=10,
            )
            story.append(Paragraph(_escape(finding.evidence), evidence_style))
            story.append(Spacer(1, 0.05 * inch))

            story.append(Paragraph("<b>Remediation:</b>", body_style))
            story.append(Paragraph(_escape(finding.remediation), body_style))
            story.append(Spacer(1, 0.3 * inch))

    # ── Appendix ──────────────────────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("Appendix — Scan Metadata", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0")))
    story.append(Spacer(1, 0.2 * inch))

    appendix_data = [
        ["Scanner Version", m.scanner_version],
        ["Scan Start", m.scan_start],
        ["Scan End", m.scan_end],
        ["Targets Requested", ", ".join(m.targets_requested)],
        ["Ports Scanned", m.ports_scanned],
        ["CVSS Threshold", str(m.cvss_threshold)],
        ["Authorization Confirmed", str(m.authorization_confirmed)],
    ]
    at = Table(appendix_data, colWidths=[2 * inch, 4.5 * inch])
    at.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(at)
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(DISCLAIMER, disclaimer_style))

    doc.build(story)
    console.print(f"  [green]✓[/green] PDF report saved: {path}")
    return path


# ── Helpers ───────────────────────────────────────────────────────────────────

def _severity_pie_chart(summary) -> Drawing | None:
    """Create a severity distribution pie chart."""
    from reportlab.lib import colors as rl_colors
    from reportlab.graphics.shapes import Drawing, String
    from reportlab.graphics.charts.piecharts import Pie

    data = [
        summary.critical_count,
        summary.high_count,
        summary.medium_count,
        summary.low_count,
        summary.info_count,
    ]
    if sum(data) == 0:
        return None

    labels = ["Critical", "High", "Medium", "Low", "Info"]
    chart_colors = [
        rl_colors.HexColor("#DC2626"),
        rl_colors.HexColor("#EA580C"),
        rl_colors.HexColor("#D97706"),
        rl_colors.HexColor("#2563EB"),
        rl_colors.HexColor("#6B7280"),
    ]

    d = Drawing(400, 200)
    pie = Pie()
    pie.x = 100
    pie.y = 15
    pie.width = 150
    pie.height = 150
    pie.data = data
    pie.labels = [f"{l} ({v})" for l, v in zip(labels, data) if v > 0]

    # Filter out zero-count slices
    non_zero_colors = [c for c, v in zip(chart_colors, data) if v > 0]
    pie.data = [v for v in data if v > 0]

    for i, c in enumerate(non_zero_colors):
        pie.slices[i].fillColor = c
        pie.slices[i].strokeColor = rl_colors.white
        pie.slices[i].strokeWidth = 2

    d.add(pie)
    return d


def _risk_color(score: float):
    from reportlab.lib import colors as rl_colors
    if score >= 9.0:
        return rl_colors.HexColor("#DC2626")
    elif score >= 7.0:
        return rl_colors.HexColor("#EA580C")
    elif score >= 4.0:
        return rl_colors.HexColor("#D97706")
    elif score > 0:
        return rl_colors.HexColor("#2563EB")
    return rl_colors.HexColor("#22C55E")


def _escape(text: str) -> str:
    """Escape XML special characters for ReportLab Paragraph."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _truncate(text: str, max_len: int) -> str:
    """Truncate text with ellipsis if needed."""
    return text if len(text) <= max_len else text[: max_len - 1] + "…"
